- bootstrap/main.tf
- bootstrap/values.tf
- main.tf
- remove wait = true in main.tf
This line seems to pose problems when we add configuration to Argo CD between the bootstrap and the “normal” module which causes Argo CD pods to restart (because the Argo CD provider seems to lose its port forward)
- remove obsolete value in value.tf
- get name from the chart in bootstrap/main.tf
> (fix) small update

- bootstrap/variables.tf
The main issue this fixes is when an "oidc" module requires argocd_bootstrap
(ex. keycloak), we can't pass the oidc config as a variable here.
Since we have to maintain separate variables.tf files for bootstrap and main,
this commit removes all variables we don't need in bootstrap.
> fix!: separate variables for bootstrap module

- README.adoc
- main.tf
- variables.tf
autosync in argocd is set to false by default
This feature has been test on a scaleway instance
> feat: introduce a variable to set auto sync on the Argo CD application resource

- README.adoc
- README.md
- locals.tf
- variables.tf
* feat!: flatten user interface by dropping usage of `var.argocd` and using standard vars instead
* feat!: drop `domain` var, build this based on devops stack ingress conventions and cluster name
* feat: document variable usage
* feat!: make some new variables now mandatory
see README.md for example
> feat!: refact main argocd module

- README.adoc
- bootstrap/README.adoc
- bootstrap/locals.tf
- locals.tf
This is just a proposition and has not been tested, although it is such a small change that in theory it should work :wink:
I'll explain my reasoning behind this. While refactoring the Keycloak and AWS OIDC modules, I added the option to let the modules themselves create an administrator group in their user pools. I named said group `devops-stack-admins` a I said to myself that these users would have administrative access to more than Argo CD, so it seemed to me that the `argocd-admin` name was not clear enough. With this change, any cluster deployed with the users and groups from those modules would have access to Argo CD without needing to add a policy CSV on the root code, which would facilitate tests and the deployment of ephemeral clusters, I think.
An alternative to replacing …
> feat: add new default administrator group

- README.adoc
- locals.tf
- main.tf
- outputs.tf
- variables.tf
Currently, a single account `pipeline` is created and given admin role and a token for API access. This PR allows passing a list of account names to the optional `extra_accounts` variable. Tokens are generated for these accounts for API access and returned using `extra_tokens` output.
> feat: support extra accounts token generation

- README.adoc
- bootstrap/README.adoc
- locals.tf
- variables.tf
Install the camptocamp helmfile plugin that integrates support for SOPS. This replaces the manual addition to helm_values that we're already using in multiple deployments. If the plugin in unused, the overhead should be negligible.
This is an 
No when not using helmfile, the addition of the helmfile plugin has no influence on existing argocd installations as long as no `helmfile.yaml` files are present in appplications.
YES when already using the helmfile via helm_values, the custom configuration should be removed from the call to this module to avoid duplication, and the IAM role or AAD pod identity should be passed to the module.
> feat!: add helmfile-sops custom plugin installation

- README.adoc
- variables.tf
[On my last PR](https://github.com/camptocamp/devops-stack-module-argocd/pull/56), when I added the `rbac` variable, I did no include a default value because I thought it would not be needed since we had a optionals on the variable structure. On a few tests later, I noticed that was not the case, so I this PR fixes that.
> fix: add default value to the rbac variable

- README.adoc
- variables.tf
When I added the variable `ssh_known_hosts`, I set the default as an empty string. This had the effect of removing all the default known hosts on the chart of Argo CD. Setting this value to `null` allows the default hosts to be deployed.
Still, if this variable is set, only the hosts that are passed will be set and you will need to add the hosts you need from the default values manually. I consider this a desirable effect, since it gives the user the chance to lock out its Argo CD and to only deploy the known hosts it wants, similarly to what the chart provides.
> fix: change default to null to not remove the default known_hosts

- README.adoc
- bootstrap/README.adoc
- locals.tf
Using the `cm` value to enable the web-terminal does not work because we also set the `server.config` value. The problem with this, is that [this condition](https://github.com/argoproj/argo-helm/blob/4afebb25f60aeeadb7c4365ab2fc1824185d0aa8/charts/argo-cd/templates/argocd-server/clusterrole.yaml#L31) would not work because of the `coalesce()` and the `ClusterRole` was created without the required permissions.
Because of this, I put the `exec.enabled` and the `admin.enabled` inside the `server.config` value.
> fix: fix the activation of the web-terminal on Argo CD

- bootstrap/README.adoc
- bootstrap/locals.tf
- bootstrap/main.tf
- bootstrap/outputs.tf
- bootstrap/terraform.tf
- bootstrap/variables.tf
- locals.tf
- main.tf
- variables.tf
This PR is still related to the preparation for the centralized Argo CD model. It does the following:
- Adds support to create an AppProject inside the bootstrap module that can then be used by the other DevOps Stack modules, including the final Argo CD.
- Like on other modules, adds labels to the Argo CD application to better organize it on the web UI.
- Adds a new variable `high_availability` to enable the HA mode of Argo CD. _The behavior of this variable is better described on its description_.
- Adds a new variable `resources` to set requests and limits for the components of Argo CD:
- We discussed that this could be added in a separate PR, but I was required to add it here because the Horizontal Pod Autoscaler requires requests to know if it needs to scale up or down a pod (this is …
> feat: add way to create and use unified AppProject, add labels and add support for HA mode

- README.adoc
- bootstrap/README.adoc
- bootstrap/variables.tf
The previous release has an issue with the bootstrap variant that prevents the instatiation of the module when that variable `argocd_projects` is not defined.
This PR modifies the validation condition to always return `true` when the variable is not defined in the instantiation.
> fix(bootstrap): fix the validation of `argocd_projects` when nothing is passed

- README.adoc
- locals.tf
- variables.tf
This fixes the missing metrics on the Argo CD dashboard that we deploy by default for Grafana.
I also increased the limits/requests for the Application Controller and Repo Server components, since they were always breaking (OOMKilled or simply CPU throttling), even on a barebones cluster.
> fix: add ServiceMonitors to fix missing metrics on Prometheus and adjust default resources requests/limits

- README.adoc
- bootstrap/README.adoc
- bootstrap/main.tf
- bootstrap/outputs.tf
- bootstrap/variables.tf
- main.tf
- variables.tf
Three commits compose this PR:
- **fix!: hardcode the release name to remove the destination cluster**
I found out that Argo CD passes the name of the application as a value to set the Helm chart. This means that all the templating that used `{ $.Release.Name }` would resolve to the name given to Argo CD application.
In a multicluster deployment, using a single Argo CD, the names of the applications must be different. We solved that by appending the cluster name to the default application name when deploying on different clusters than `in-cluster`. However, this resulted in multiple problems for deployments that depended on the name of the application being static, so this solves that.
This is a breaking change because sometimes this requires an application to be deleted and recreated.
- …
> fix!: change the default cluster issuer, remove the namespace variable and hardcode the Helm release name

- README.adoc
- bootstrap/README.adoc
- locals.tf
- variables.tf
Hello, 
We have a need to use URLs without the **.apps.** part, in order to achieve that without introducing a breaking change we propose a new variable **subdomain** that defaults to apps, that way we can set it to an empty string on our side.
> feat: add a subdomain variable

- README.adoc
- bootstrap/README.adoc
- locals.tf
- variables.tf
We found that having limits by default on Argo CD could potentially break a bootstrap of clusters with a lot of Applications and/or ApplicationSets and then it was really difficult to increase the limits while Argo CD was hanging and starving for resources.
:warning: **Do a _Rebase and merge_**
> fix: adjust the resources and remove default limits

- README.adoc
- bootstrap/README.adoc
- locals.tf
- variables.tf
This PR allows more granularity in setting the requests/limits for the `repo-server` component by allowing to set the requests/limits separately for the Config Management Plugins attached to said component.
> feat: add variables to set resource requests/limits on plugins

- README.adoc
- bootstrap/README.adoc
- charts/argocd/values.yaml
This PR updates the Prometheus rule for monitoring Argo CD applications' sync status. The current rule checks if there is exactly one application that is out of sync. This update replaces it with a more flexible rule that triggers when there is at least one out-of-sync application, while also ensuring the presence of the namespace label for better context in alerts.
> feat: update prometheus rule to be more flexible

- README.adoc
- bootstrap/README.adoc
- charts/argocd/dashboards/global.json
This PR fixes the dashboards that relied on AngularJS, which has been deprecated and removed in Grafana v11.0. The necessary updates have been made to ensure these dashboards are fully compatible with the latest version of Grafana, preventing any functionality issues due to the removal of AngularJS support.
> fix: grafana panels uses angular deprecated plugin

- README.adoc
- bootstrap/README.adoc
- charts/argocd/templates/grafana-dashboard.yaml
Grafana does not manage/support to have multiple dashboards with the same filename so I added the release name as a prefix to avoid duplicates with other modules.
> fix(charts): add release in file name to avoid duplicates
